// some random prophecies as an inspiration for user

const sampleProphecies = [
    "You will soon understand blockchain. Or pretend to, just like everyone else",
    "You will explain blockchain to your grandma. She will still think it's about knitting",
    "Soon, your most valuable asset will be your ability to pronounce 'cryptocurrency' correctly",
    "Your future is decentralized, just like your last family reunion",
    "Invest in blockchain... or just enjoy this time capsule. Both are equally delicious",
    "In the future, your blockchain knowledge will be worth more than gold... in very niche conversations",
    "You will soon find the key to wealth: it's somewhere on the blockchain. Happy hunting!",
    "Your cat will understand blockchain before you do. Prepare to be outsmarted",
    "You will soon discover that blockchain has nine lives, just like your cat",
    "Invest in blockchain or invest in cats. Both are unpredictable and may lead to obsession",
    "Your cat will launch its own cryptocurrency: MeowCoin. It will dominate the market in no time",
    "You will try to explain blockchain to your cat. It will respond with a blank stare and a request for more treats",
    "Cats and blockchain: both are mysterious, and understanding them fully is a myth",
    "Your cat will soon create a decentralized network of nap spots around your house",
    "The blockchain may be unbreakable, but your cat will find a way to disrupt it... with a single paw",
    "Your dog will create its own cryptocurrency: BarkCoin. It will fetch great returns!",
    "Your dog will soon understand blockchain better than you. Prepare for some tail-wagging lectures",
    "Your dog will soon launch a decentralized snack exchange. Bones will be the main currency",
    "In the future, your dog will mine crypto... mostly by digging holes in your backyard",
    "Investing in crypto is like teaching your dog new tricks: confusing but rewarding when it works",
    "You will soon be trading on a DEX so much, even your dog will start calling you Whale",
    "You will teach your grandma about a DEX. She will wonder why anyone would trade decks of cards online",
    "Your understanding of crypto will be so profound, you will start dreaming in smart contracts",
    "You will master Sui blockchain so well, even your coffee will start to brew itself",
    "In the future, you will explain Sui to your friends. They will think it is the newest sushi restaurant",
    "Your knowledge of Sui will be so sharp, you will start calling your cat 'Sui-perior Feline'",
    "You will navigate the Sui blockchain with the grace of a ninja, silently and efficiently",
    "Your future is as bright as Sui decentralized future. Sunglasses recommended",
    "You will soon realize that understanding Sui blockchain is easier than assembling flat-pack furniture",
    "Your understanding of timelock encryption will soon be so advanced, even your alarm clock will start respecting your secrets",
    "You will soon explain timelock encryption to your friends. They will think you are talking about a new escape room challenge",
    "Your timelock encryption skills will be so sharp, you will start locking up your to-do list... for future you to handle",
    "In the future, your use of timelock encryption will be so seamless, you will consider using it on your diary. Secrets safe for centuries!",
    "You will soon realize that understanding timelock encryption is easier than trying to assemble a 1,000-piece puzzle",
    "Your mastery of timelock encryption will make you the go-to person for securing birthday surprises",
    "In the future, you will use timelock encryption to lock up your social media during work hours. Productivity awaits!",
    "Your knowledge of timelock encryption will be so profound, even your cat will respect your digital privacy",
    "You will soon use timelock encryption to secure your secrets. Just make sure not to lock up your TV remote by accident!",
    "In the future, you will use timelock encryption to secure your holiday shopping list. No peeking!",
    "Your knowledge of timelock encryption will be so deep, you will start encrypting your grocery list. Mystery meals ahead!",
    "You will soon use timelock encryption to schedule naps. No more accidental oversleeping!",
    "In the future, your use of timelock encryption will be so precise, you will never miss a birthday surprise",
    "Your timelock encryption skills will be so legendary, even your plants will grow on a schedule",
    "Your future in crypto is so bright, you'll need timelock encryption just to manage the glare",
    "You will soon use timelock encryption to protect your crypto keys. Just make sure not to lose the unlock date!",
    "In the future, your crypto wallet will be so secure, even you will need a map and timelock encryption to find it",
    "Your knowledge of timelock encryption will be so advanced, your crypto investments will mature like fine wine",
    "In the future, you will use timelock encryption to secure your crypto gains. Time is on your side!",
    "You will soon use timelock encryption to lock up your crypto profits until the next bull run. Patience is a virtue!",
    "In the future, your use of timelock encryption will be so seamless, your crypto assets will be as secure as Fort Knox",
    "Your crypto investments will be so well-timed, even bulls will ask for your advice",
    "In the future, you will use timelock encryption to lock up your crypto during bull runs. HODL strong!",
    "Your knowledge of timelock encryption will be so advanced, you will unlock your crypto right at the peak of the bull run",
    "Your timelock encryption skills will make you the go-to person for securing crypto during bull runs. No more FOMO!",
    "In the future, your crypto gains will be so impressive, even bulls will tip their hats to you",
    "You will use timelock encryption to protect your crypto from bull run excitement. It is like giving your wallet a tranquilizer",
    "Your understanding of timelock encryption will be so deep, you will navigate bull runs with the grace of a matador",
    "You will soon time your crypto investments so well, bulls will start following you on social media",
    "In the future, you will use timelock encryption to lock your crypto until the end of the bull run. Patience is the new profit",
    "Your crypto will soon go to the moon, just do not forget to use timelock encryption for a safe landing",
    "You will soon use timelock encryption to secure your crypto until it reaches lunar heights. Moon boots optional",
    "You will explain timelock encryption to your friends. They will think you are planning a lunar expedition",
    "Your timelock encryption skills will make sure your crypto reaches the moon safely, no space suit needed",
    "In the future, your crypto will soar so high, even the moon will seem like a pit stop",
    "Your understanding of timelock encryption will be so deep, you will unlock your gains right when they touch down on the moon",
    "You will use timelock encryption to keep your crypto secure during its trip to the moon. Lunar profits await!"
];

export default class SampleProphecies {
    static getRandom() {
        return sampleProphecies[Math.floor(Math.random()*sampleProphecies.length)];
    }
}
