<template>

	<div class="row">
        <div class="col-2">
        &nbsp;
        </div>
        <div class="col-8">
		<p>
			<strong>HexCapsule &ndash; timelock encryption on the Sui blockchain</strong>
		</p>

		<p>
		Timelock encryption is a cryptographic technique that allows data to be encrypted in such a way that it can only be decrypted 
		after a specified period has elapsed. This method ensures that the encrypted information remains inaccessible until the predetermined 
		time has passed, regardless of who possesses the encrypted data. It is commonly used in scenarios where there is a need to delay access 
		to sensitive information or to enforce time-based policies on data access.
		</p>

		<p>
		<strong>Secure Delayed Messages: </strong>Ensuring messages cannot be read until a future date.
		</p>

		<p>
		HexCapsule relies on <a href="https://drand.love/about/" target="_blank">Drand</a> for encrypting keys on the front-end and generating future private keys 
		for decrypting data on the blockchain.
		</p>

		<p>
		<strong>Drand</strong>, short for "Distributed Randomness Beacon," is a cryptographic service that provides publicly verifiable, unbiased, 
		and unpredictable random numbers. The randomness generated by drand is distributed and secured by a network of independent and 
		decentralized participants, ensuring its trustworthiness and resistance to tampering.
		</p>

		<p>
			<strong>Cryptography Flow</strong>
		</p>

		<p>
			<strong>Encryption</strong><br/>
			<span style="background-color: white; display: inline-block;"><img src="/encryption.png" style="width: 836px; max-width: 90%;" /></span>		
		</p>

		<p>
			<strong>Decryption</strong><br/>
			<span style="background-color: white; display: inline-block;"><img src="/decryption.png" style="width: 836px; max-width: 90%;" /></span>
		</p>

		<p><strong>Use Cases</strong></p>

		<p>
			<ul>
				<li>Secure Time-Delayed Communication</li>
				<li>Transfer of assets/password upon death</li>
				<li>Whistleblower Protection</li>
				<li>Time-locked Contracts</li>
				<li>Content Release</li>
				<li>Timed Quizzes and Exams</li>
			</ul>

			If you can think of any more cool use cases, <a href="https://twitter.com/suidouble" target="_blank">let us know</a> on twitter.
		</p>


		<p>
			<strong>Proof on Chain</strong><br/>

			Hex.Capsule encrypts secret messages on the client side, hashing the message for a specific future drand round. It sends only the encrypted message to the blockchain.
		</p>
		<p>
			<span style="background-color: white; display: inline-block;"><img src="/blockchain_secret.png" style="width: 836px; max-width: 90%;" /></span>
		</p>
		<p>
			Once decrypted in the future, it becomes available for everyone to check.
		</p>
		<p>
			<span style="background-color: white; display: inline-block;"><img src="/blockchain_decrypted.png" style="width: 836px; max-width: 90%;" /></span>
		</p>

		</div>
        <div class="col-2">
        &nbsp;
        </div>
	</div>

</template>

<script>

export default {
	name: 'About',
	title: 'About Us',
	authRequired: false,
	path: '/about',

	props: {
	},
	data() {
		return {
			isActive: false,
		}
	},
	methods: {
	},
	mounted() {
	}
}
</script>
<style scoped>

</style>

